package com.example.ui.localization

import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage(val code: String, val displayName: String, val direction: LayoutDirection) {
    AR("ar", "العربية", LayoutDirection.Rtl),
    EN("en", "English", LayoutDirection.Ltr),
    FR("fr", "Français", LayoutDirection.Ltr),
    ES("es", "Español", LayoutDirection.Ltr),
    DE("de", "Deutsch", LayoutDirection.Ltr)
}

data class TranslatableStrings(
    val appName: String,
    val addArticle: String,
    val editArticle: String,
    val titleLabel: String,
    val titlePlaceholder: String,
    val contentLabel: String,
    val contentPlaceholder: String,
    val imageOptionLabel: String,
    val imageUrlLabel: String,
    val imageUrlPlaceholder: String,
    val orLabel: String,
    val pickLocalImage: String,
    val selectLanguage: String,
    val saveButton: String,
    val deleteButton: String,
    val emptyStateTitle: String,
    val emptyStateSubtitle: String,
    val readMore: String,
    val searchPlaceholder: String,
    val articleSavedSuccess: String,
    val articleDeletedSuccess: String,
    val allFieldsRequired: String,
    val cancel: String,
    val categoryLabel: String,
    val generalCategory: String,
    val techCategory: String,
    val scienceCategory: String,
    val healthCategory: String,
    val cultureCategory: String,
    val articleDetails: String,
    val selectCategory: String,
    val customImageOption: String,
    val enterUrlOption: String,
    val sampleImageUrlOption: String,
    val useSampleImage: String,
    val chooseSampleTitle: String,
    
    // Login system strings
    val loginTitle: String,
    val loginSubtitle: String,
    val registerTitle: String,
    val registerSubtitle: String,
    val emailLabel: String,
    val emailPlaceholder: String,
    val passwordLabel: String,
    val passwordPlaceholder: String,
    val loginButton: String,
    val registerButton: String,
    val dontHaveAccount: String,
    val alreadyHaveAccount: String,
    val invalidEmailPassword: String,
    val loginSuccess: String,
    val registerSuccess: String,
    val logoutButton: String,
    val googleSignInButton: String,
    val guestSignInButton: String,
    val orDividerLabel: String,
    val settingsTitle: String,
    val settingsThemeLabel: String,
    val settingsThemeSystem: String,
    val settingsThemeLight: String,
    val settingsThemeDark: String,
    val settingsLanguageLabel: String,
    val settingsResetDataLabel: String,
    val settingsResetDataDesc: String,
    val settingsResetButton: String,
    val settingsResetSuccess: String,
    val settingsAboutLabel: String,
    val settingsAboutDesc: String,
    val settingsCloseButton: String,
    val settingsButton: String
)

object LocalizationManager {
    private val arabicStrings = TranslatableStrings(
        appName = "محفظة المقالات",
        addArticle = "إضافة مقال",
        editArticle = "تعديل المقال",
        titleLabel = "عنوان المقال",
        titlePlaceholder = "أدخل عنوان المقال...",
        contentLabel = "النص الكامل للمقال",
        contentPlaceholder = "اكتب أو الصق نص المقال الكامل هنا...",
        imageOptionLabel = "غلاف المقال (صورة مصغرة)",
        imageUrlLabel = "رابط الصورة الذكي (URL)",
        imageUrlPlaceholder = "أدخل رابط الصورة (مثل: https://images.unsplash.com/...)",
        orLabel = "أو",
        pickLocalImage = "اختر صورة سريعة",
        selectLanguage = "لغة التطبيق",
        saveButton = "حفظ المقال",
        deleteButton = "حذف المقال",
        emptyStateTitle = "لا توجد مقالات محفوظة",
        emptyStateSubtitle = "ابدأ بكتابة وحفظ مقالك الأول لقراءته لاحقاً في أي وقت!",
        readMore = "اقرأ المقال الكامل",
        searchPlaceholder = "ابحث بالعنوان أو المحتوى...",
        articleSavedSuccess = "تم حفظ المقال بنجاح!",
        articleDeletedSuccess = "تم حذف المقال بنجاح!",
        allFieldsRequired = "يرجى ملء حقول العنوان والنص للمقال!",
        cancel = "إلغاء",
        categoryLabel = "التصنيف",
        generalCategory = "عام",
        techCategory = "تقنية",
        scienceCategory = "علوم",
        healthCategory = "صحة",
        cultureCategory = "ثقافة",
        articleDetails = "تفاصيل المقال",
        selectCategory = "اختر التصنيف المناسب",
        customImageOption = "إدخال رابط مخصص للصورة",
        enterUrlOption = "رابط صورة خارجي",
        sampleImageUrlOption = "اختر صورة معبرة جاهزة",
        useSampleImage = "استخدم هذه الصورة الجاهزة",
        chooseSampleTitle = "اختر غلافًا جاهزًا للمقال",
        
        // Login system
        loginTitle = "مرحباً بك مجدداً",
        loginSubtitle = "سجل دخولك الآن للوصول إلى محفظة مقالاتك الآمنة",
        registerTitle = "إنشاء حساب جديد",
        registerSubtitle = "احفظ مقالاتك واقرأها من أي مكان وفي أي وقت",
        emailLabel = "البريد الإلكتروني",
        emailPlaceholder = "أدخل بريدك الإلكتروني (مثل: user@example.com)",
        passwordLabel = "كلمة المرور",
        passwordPlaceholder = "أدخل كلمة المرور الخاصة بك",
        loginButton = "تسجيل الدخول",
        registerButton = "إنشاء الحساب",
        dontHaveAccount = "ليس لديك حساب؟ سجل الآن",
        alreadyHaveAccount = "لديك حساب بالفعل؟ سجل دخولك",
        invalidEmailPassword = "البريد الإلكتروني أو كلمة المرور غير صالحة!",
        loginSuccess = "تم تسجيل الدخول بنجاح!",
        registerSuccess = "تم إنشاء الحساب بنجاح!",
        logoutButton = "تسجيل الخروج",
        googleSignInButton = "تسجيل الدخول باستخدام Google",
        guestSignInButton = "الدخول كضيف زائر",
        orDividerLabel = "أو عبر الطرق البديلة",
        settingsTitle = "إعدادات التطبيق",
        settingsThemeLabel = "مظهر التطبيق",
        settingsThemeSystem = "تلقائي (حسب النظام)",
        settingsThemeLight = "نهاري (فاتح)",
        settingsThemeDark = "ليلي (داكن)",
        settingsLanguageLabel = "لغة واجهة التطبيق",
        settingsResetDataLabel = "إعادة تعيين قاعدة البيانات",
        settingsResetDataDesc = "سيتم حذف جميع مقالاتك المحفوظة محلياً بشكل دائم وغير قابل للاستعادة.",
        settingsResetButton = "حذف جميع المقالات",
        settingsResetSuccess = "تم تفريغ وحذف جميع المقالات بنجاح!",
        settingsAboutLabel = "حول التطبيق",
        settingsAboutDesc = "تطبيق محفظة مقالات مميز واحترافي مصمم ليوفر لك تجربة كتابة وتدوين وقراءة متكاملة مع دعم كامل للغات المتعددة والمزامنة المحلية.",
        settingsCloseButton = "إغلاق نافذة الإعدادات",
        settingsButton = "الإعدادات"
    )

    private val englishStrings = TranslatableStrings(
        appName = "Article Portfolio",
        addArticle = "Add Article",
        editArticle = "Edit Article",
        titleLabel = "Article Title",
        titlePlaceholder = "Enter article title...",
        contentLabel = "Full Article Text",
        contentPlaceholder = "Type or paste the full content here...",
        imageOptionLabel = "Article Cover (Thumbnail)",
        imageUrlLabel = "Smart Image URL",
        imageUrlPlaceholder = "Enter image URL (e.g., https://images.unsplash.com/...)",
        orLabel = "OR",
        pickLocalImage = "Quick Image Selection",
        selectLanguage = "App Language",
        saveButton = "Save Article",
        deleteButton = "Delete Article",
        emptyStateTitle = "No articles saved yet",
        emptyStateSubtitle = "Start by writing and saving your first article to read later!",
        readMore = "Read Full Article",
        searchPlaceholder = "Search by title or content...",
        articleSavedSuccess = "Article saved successfully!",
        articleDeletedSuccess = "Article deleted successfully!",
        allFieldsRequired = "Please fill in both title and content fields!",
        cancel = "Cancel",
        categoryLabel = "Category",
        generalCategory = "General",
        techCategory = "Tech",
        scienceCategory = "Science",
        healthCategory = "Health",
        cultureCategory = "Culture",
        articleDetails = "Article Details",
        selectCategory = "Select Category",
        customImageOption = "Custom Image URL",
        enterUrlOption = "External Image Link",
        sampleImageUrlOption = "Select Featured Cover",
        useSampleImage = "Use Featured Cover",
        chooseSampleTitle = "Choose a ready-made cover",
        
        // Login system
        loginTitle = "Welcome Back",
        loginSubtitle = "Sign in to access your secure article portfolio",
        registerTitle = "Create New Account",
        registerSubtitle = "Keep your articles safe and read them anytime",
        emailLabel = "Email Address",
        emailPlaceholder = "Enter your email (e.g., user@example.com)",
        passwordLabel = "Password",
        passwordPlaceholder = "Enter your password",
        loginButton = "Sign In",
        registerButton = "Sign Up",
        dontHaveAccount = "Don't have an account? Sign up",
        alreadyHaveAccount = "Already have an account? Sign in",
        invalidEmailPassword = "Invalid email or password!",
        loginSuccess = "Logged in successfully!",
        registerSuccess = "Account created successfully!",
        logoutButton = "Sign Out",
        googleSignInButton = "Sign in with Google",
        guestSignInButton = "Continue as Guest",
        orDividerLabel = "OR CONTINUE WITH",
        settingsTitle = "App Settings",
        settingsThemeLabel = "App Theme",
        settingsThemeSystem = "System (Default)",
        settingsThemeLight = "Light Mode",
        settingsThemeDark = "Dark Mode",
        settingsLanguageLabel = "App Language",
        settingsResetDataLabel = "Reset Database",
        settingsResetDataDesc = "Permanently wipe all locally saved articles and reset your workspace data.",
        settingsResetButton = "Delete All Articles",
        settingsResetSuccess = "All data cleared successfully!",
        settingsAboutLabel = "About Application",
        settingsAboutDesc = "A premium article writing and cataloging portfolio built using modern Material Design. Keep track of inspiration and distribute knowledge dynamically.",
        settingsCloseButton = "Close Settings",
        settingsButton = "Settings"
    )

    private val frenchStrings = TranslatableStrings(
        appName = "Portefeuille d'Articles",
        addArticle = "Ajouter un Article",
        editArticle = "Modifier l'Article",
        titleLabel = "Titre de l'Article",
        titlePlaceholder = "Entrez le titre de l'article...",
        contentLabel = "Texte Complet de l'Article",
        contentPlaceholder = "Écrivez ou collez le contenu complet ici...",
        imageOptionLabel = "Couverture de l'Article",
        imageUrlLabel = "URL de l'Image",
        imageUrlPlaceholder = "Entrez l'URL de l'image (ex: https://images.unsplash.com/...)",
        orLabel = "OU",
        pickLocalImage = "Sélection Rapide d'Image",
        selectLanguage = "Langue de l'App",
        saveButton = "Enregistrer l'Article",
        deleteButton = "Supprimer l'Article",
        emptyStateTitle = "Aucun article enregistré",
        emptyStateSubtitle = "Commencez à rédiger et à enregistrer votre premier article !",
        readMore = "Lire l'Article Complet",
        searchPlaceholder = "Rechercher par titre ou contenu...",
        articleSavedSuccess = "Article enregistré avec succès !",
        articleDeletedSuccess = "Article supprimé avec succès !",
        allFieldsRequired = "Veuillez remplir le titre et le contenu !",
        cancel = "Annuler",
        categoryLabel = "Catégorie",
        generalCategory = "Général",
        techCategory = "Technologie",
        scienceCategory = "Science",
        healthCategory = "Santé",
        cultureCategory = "Culture",
        articleDetails = "Détails de l'Article",
        selectCategory = "Sélectionnez une catégorie",
        customImageOption = "URL d'image personnalisée",
        enterUrlOption = "Lien d'image externe",
        sampleImageUrlOption = "Sélectionner une couverture",
        useSampleImage = "Utiliser cette couverture",
        chooseSampleTitle = "Choisir une couverture prête",
        
        // Login system
        loginTitle = "Bon retour",
        loginSubtitle = "Connectez-vous pour accéder à votre portefeuille d'articles",
        registerTitle = "Créer un compte",
        registerSubtitle = "Conservez vos articles en toute sécurité",
        emailLabel = "Adresse Email",
        emailPlaceholder = "Entrez votre email (ex: user@example.com)",
        passwordLabel = "Mot de passe",
        passwordPlaceholder = "Entrez votre mot de passe",
        loginButton = "Se connecter",
        registerButton = "S'inscrire",
        dontHaveAccount = "Pas de compte ? S'inscrire",
        alreadyHaveAccount = "Déjà un compte ? Se connecter",
        invalidEmailPassword = "Email ou mot de passe invalide !",
        loginSuccess = "Connexion réussie !",
        registerSuccess = "Compte créé avec succès !",
        logoutButton = "Se déconnecter",
        googleSignInButton = "Se connecter avec Google",
        guestSignInButton = "Continuer en tant qu'invité",
        orDividerLabel = "OU CONTINUER AVEC",
        settingsTitle = "Paramètres de l'application",
        settingsThemeLabel = "Thème de l'application",
        settingsThemeSystem = "Système (Défaut)",
        settingsThemeLight = "Mode Clair",
        settingsThemeDark = "Mode Sombre",
        settingsLanguageLabel = "Langue de l'App",
        settingsResetDataLabel = "Réinitialiser la Base",
        settingsResetDataDesc = "Effacer définitivement tous les articles enregistrés localement.",
        settingsResetButton = "Supprimer Tous les Articles",
        settingsResetSuccess = "Toutes les données ont été effacées !",
        settingsAboutLabel = "À Propos de l'App",
        settingsAboutDesc = "Un portefeuille haut de gamme d'écriture et de catalogage d'articles utilisant Material Design moderne.",
        settingsCloseButton = "Fermer les Paramètres",
        settingsButton = "Paramètres"
    )

    private val spanishStrings = TranslatableStrings(
        appName = "Portafolio de Artículos",
        addArticle = "Agregar Artículo",
        editArticle = "Editar Artículo",
        titleLabel = "Título del Artículo",
        titlePlaceholder = "Ingrese el título...",
        contentLabel = "Texto Completo del Artículo",
        contentPlaceholder = "Escriba o pegue el contenido aquí...",
        imageOptionLabel = "Portada del Artículo",
        imageUrlLabel = "URL de la Imagen",
        imageUrlPlaceholder = "Ingrese la URL (ej: https://images.unsplash.com/...)",
        orLabel = "O",
        pickLocalImage = "Selección Rápida",
        selectLanguage = "Idioma de la App",
        saveButton = "Guardar Artículo",
        deleteButton = "Eliminar Artículo",
        emptyStateTitle = "No hay artículos guardados",
        emptyStateSubtitle = "¡Comience escribiendo y guardando su primer artículo para leerlo después!",
        readMore = "Leer Artículo Completo",
        searchPlaceholder = "Buscar por título o contenido...",
        articleSavedSuccess = "¡Artículo guardado con éxito!",
        articleDeletedSuccess = "¡Artículo eliminado con éxito!",
        allFieldsRequired = "¡Por favor complete el título y el contenido!",
        cancel = "Cancelar",
        categoryLabel = "Categoría",
        generalCategory = "General",
        techCategory = "Tecnología",
        scienceCategory = "Ciencia",
        healthCategory = "Salud",
        cultureCategory = "Cultura",
        articleDetails = "Detalles del Artículo",
        selectCategory = "Seleccione Categoría",
        customImageOption = "URL de imagen personalizada",
        enterUrlOption = "Enlace de imagen externo",
        sampleImageUrlOption = "Seleccionar portada",
        useSampleImage = "Usar esta portada",
        chooseSampleTitle = "Elegir una portada prefabricada",
        
        // Login system
        loginTitle = "Bienvenido de nuevo",
        loginSubtitle = "Inicie sesión para acceder a su portafolio seguro",
        registerTitle = "Crear nueva cuenta",
        registerSubtitle = "Mantenga sus artículos seguros y léalos en cualquier momento",
        emailLabel = "Correo electrónico",
        emailPlaceholder = "Ingrese su correo (ej: user@example.com)",
        passwordLabel = "Contraseña",
        passwordPlaceholder = "Ingrese su contraseña",
        loginButton = "Iniciar Sesión",
        registerButton = "Registrarse",
        dontHaveAccount = "¿No tiene una cuenta? Regístrese",
        alreadyHaveAccount = "¿Ya tiene una cuenta? Inicie sesión",
        invalidEmailPassword = "¡Correo electrónico o contraseña inválidos!",
        loginSuccess = "¡Inicio de sesión exitoso!",
        registerSuccess = "¡Cuenta creada con éxito!",
        logoutButton = "Cerrar Sesión",
        googleSignInButton = "Iniciar sesión con Google",
        guestSignInButton = "Continuar como invitado",
        orDividerLabel = "O CONTINUAR CON",
        settingsTitle = "Configuración",
        settingsThemeLabel = "Tema de la aplicación",
        settingsThemeSystem = "Sistema (Predeterminado)",
        settingsThemeLight = "Modo Claro",
        settingsThemeDark = "Modo Oscuro",
        settingsLanguageLabel = "Idioma de la aplicación",
        settingsResetDataLabel = "Restablecer base de datos",
        settingsResetDataDesc = "Borre de forma permanente todos los artículos guardados localmente.",
        settingsResetButton = "Eliminar todos los artículos",
        settingsResetSuccess = "¡Todos los datos borrados correctamente!",
        settingsAboutLabel = "Acerca de la aplicación",
        settingsAboutDesc = "Un portafolio premium de escritura y catalogación de artículos diseñado con Material Design moderno.",
        settingsCloseButton = "Cerrar configuración",
        settingsButton = "Configuración"
    )

    private val germanStrings = TranslatableStrings(
        appName = "Artikel-Portfolio",
        addArticle = "Artikel hinzufügen",
        editArticle = "Artikel bearbeiten",
        titleLabel = "Artikeltitel",
        titlePlaceholder = "Artikeltitel eingeben...",
        contentLabel = "Vollständiger Artikeltext",
        contentPlaceholder = "Inhalt hier eingeben oder einfügen...",
        imageOptionLabel = "Artikel-Cover (Vorschaubild)",
        imageUrlLabel = "Bild-URL",
        imageUrlPlaceholder = "Bild-URL eingeben (z.B. https://images.unsplash.com/...)",
        orLabel = "ODER",
        pickLocalImage = "Schnellauswahl Bild",
        selectLanguage = "App-Sprache",
        saveButton = "Artikel保存", // updated below
        deleteButton = "Artikel löschen",
        emptyStateTitle = "Noch keine Artikel gespeichert",
        emptyStateSubtitle = "Schreiben und speichern Sie Ihren ersten Artikel, um ihn später zu lesen!",
        readMore = "Ganzen Artikel lesen",
        searchPlaceholder = "Suchen nach Titel oder Inhalt...",
        articleSavedSuccess = "Artikel erfolgreich gespeichert!",
        articleDeletedSuccess = "Artikel erfolgreich gelöscht!",
        allFieldsRequired = "Bitte füllen Sie Titel und Inhalt aus!",
        cancel = "Abbrechen",
        categoryLabel = "Kategorie",
        generalCategory = "Allgemein",
        techCategory = "Technologie",
        scienceCategory = "Wissenschaft",
        healthCategory = "Gesundheit",
        cultureCategory = "Kultur",
        articleDetails = "Artikel-Details",
        selectCategory = "Kategorie auswählen",
        customImageOption = "Benutzerdefinierte Bild-URL",
        enterUrlOption = "Externer Bildlink",
        sampleImageUrlOption = "Titelbild auswählen",
        useSampleImage = "Dieses Cover verwenden",
        chooseSampleTitle = "Wählen Sie ein fertiges Cover",
        
        // Login system
        loginTitle = "Willkommen zurück",
        loginSubtitle = "Melden Sie sich an, um auf Ihr sicheres Portfolio zuzugreifen",
        registerTitle = "Neues Konto erstellen",
        registerSubtitle = "Bewahren Sie Ihre Artikel sicher auf und lesen Sie sie jederzeit",
        emailLabel = "E-Mail-Adresse",
        emailPlaceholder = "Geben Sie Ihre E-Mail ein (z. B. user@example.com)",
        passwordLabel = "Passwort",
        passwordPlaceholder = "Geben Sie Ihr Passwort ein",
        loginButton = "Anmelden",
        registerButton = "Registrieren",
        dontHaveAccount = "Noch kein Konto? Registrieren",
        alreadyHaveAccount = "Bereits ein Konto? Anmelden",
        invalidEmailPassword = "Ungültige E-Mail-Adresse oder Passwort!",
        loginSuccess = "Erfolgreich angemeldet!",
        registerSuccess = "Konto erfolgreich erstellt!",
        logoutButton = "Abmelden",
        googleSignInButton = "Mit Google anmelden",
        guestSignInButton = "Als Gast fortfahren",
        orDividerLabel = "ODER WEITER WITH",
        settingsTitle = "App-Einstellungen",
        settingsThemeLabel = "App-Design",
        settingsThemeSystem = "System (Standard)",
        settingsThemeLight = "Heller Modus",
        settingsThemeDark = "Dunkler Modus",
        settingsLanguageLabel = "App-Sprache",
        settingsResetDataLabel = "Datenbank zurücksetzen",
        settingsResetDataDesc = "Löschen Sie dauerhaft alle lokal gespeicherten Artikel.",
        settingsResetButton = "Alle Artikel löschen",
        settingsResetSuccess = "Alle Daten wurden erfolgreich gelöscht!",
        settingsAboutLabel = "Über die App",
        settingsAboutDesc = "Ein erstklassiges Artikelportfolio, das mit modernem Material Design für ein vollendetes Leseerlebnis entwickelt wurde.",
        settingsCloseButton = "Einstellungen schließen",
        settingsButton = "Einstellungen"
    )

    fun getStrings(language: AppLanguage): TranslatableStrings {
        return when (language) {
            AppLanguage.AR -> arabicStrings
            AppLanguage.EN -> englishStrings
            AppLanguage.FR -> frenchStrings
            AppLanguage.ES -> spanishStrings
            AppLanguage.DE -> germanStrings
        }
    }
}
